# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  microservices1:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./micro1

      strategy:
        matrix:
          node-version: [16.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

      steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          #cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      #- run: npm test
      
  microservices2:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./micro2

      strategy:
        matrix:
          node-version: [16.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

      steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          #cache: 'npm'
      - name: INSTALL DEPENDENCIES
        run: npm ci
      - name: BUILDING APP
        run: npm run build --if-present
      #- name: TESTINT APP
      #- run: npm test
      
  microservices3:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./micro3

      strategy:
        matrix:
          node-version: [16.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

      steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          #cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      #- run: npm test